python main.py \
--env_name halfcheetah-expert-v2 \
--f_epoch 30 \
--max_training_timesteps 1000000 \
--update_timestep 4000 \
--downstream 'ddpg' \
--expert_episode multiple \
--minus \
--seed 0 \
--using_icvf \
--cuda cuda:7 \
--wandb_name ddpg
